name: Run Data Sync

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
    paths:
      - scripts/nike_sync.py
      - scripts/strava.py
      - scripts/gen_json.py
      - requirements.txt

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run sync script
        run: |
          python scripts/nike_sync.py ${{ secrets.NIKE_REFRESH_TOKEN }}

      - name: Make svg GitHub profile
        run: |
          python scripts/gen_svg.py  --language zh_CN --gpx-dir ./GPX_OUT --title "Yihong0618 Running" --type github --athlete "yihong0618" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
          python scripts/gen_svg.py  --language zh_CN --gpx-dir ./GPX_OUT --title "Over 10km Runs" --type grid --athlete "yihong0618"  --output assets/grid.svg --min-distance 10.0 --special-color yellow --special-color2 red --special-distance 20 --special-distance2 40 --use-localtime

      - name: Push new runs
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add new runs"
          files: activities src/static/ scripts/data.db assets/ GPX_OUT/
          rebase: 'true'
          name: yihong0618 
          email: zouzou0208@gmail.com
